name: my-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - joblib=1.5.3
  - libcxx=21.1.8
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libopenblas=0.3.31
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.0.19
  - packaging=25.0
  - pandas=2.3.3
  - pip=26.0.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - pytz=2025.2
  - readline=8.3
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - setuptools=80.10.2
  - six=1.17.0
  - sqlite=3.51.1
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - exceptiongroup==1.3.1
      - iniconfig==2.3.0
      - pluggy==1.6.0
      - pygments==2.19.2
      - pytest==9.0.2
      - rapidfuzz==3.14.3
      - tomli==2.4.0
      - typing-extensions==4.15.0
prefix: /opt/anaconda3/envs/my-env
